export interface Walker {
  id: string;
  name: string;
  isDefault?: boolean;
}

export enum WalkMode {
  AUTO = 'Auto',
  MANUAL = 'Manual',
}

export enum PoopCondition {
  NORMAL = '正常',
  SOFT = '偏軟',
  DIARRHEA = '拉稀',
}

export interface Coordinates {
  latitude: number;
  longitude: number;
  timestamp: number;
}

export interface WalkRecord {
  id: string;
  mode: WalkMode;
  walkers: string[]; // List of walker names
  startTime: number; // Timestamp
  endTime: number; // Timestamp
  durationSeconds: number;
  routeCoordinates?: Coordinates[]; // For auto mode
  manualRouteDescription?: string; // For manual mode
  mood: string;
  hasPooped: boolean;
  poopCondition?: PoopCondition;
  notes: string;
  aiDiaryEntry?: string; // Generated by Gemini
  date: string; // ISO Date string for grouping
}

export interface WalkFormData {
  mood: string;
  hasPooped: boolean;
  poopCondition?: PoopCondition;
  notes: string;
}

export interface FirebaseConfig {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
}